### PR TITLE
Auto generate SDK reference

### PR DESCRIPTION
**Pull request by aksalj**
- added sphinx docs

### CODE REVIEW

**Comment by aksalj** [comment]
@nicholas-ngatia should we have a script/makefile to go along with this?

**Comment by nicholas-ngatia** [comment]
> @nicholas-ngatia should we have a script/makefile to go along with this?

my bad, i thought all we needed were the html files, i've added another commit with all the prerequisite files

**Comment by aksalj** [comment]
Since github pages will serve content from the `docs/` folder, I think we should have this setup in such a way the root folder for the generated HTML is `docs/`

**Comment by nicholas-ngatia** [comment]
> Since github pages will serve content from the `docs/` folder, I think we should have this setup in such a way the root folder for the generated HTML is `docs/`. For example, on the [java SDK](https://github.com/ElarianLtd/java-sdk/tree/master/docs), javadocs are generated into `docs/`

I think in that case we might have to just pull the html files from the 'build' folder and just place them there, sphinx always puts them into that folder. It shouldn't cause any issues I think

**Pull request merged**
